### ISSUE TITLE
require.async() isn't in node anymore

### ISSUE THREAD

**Issue by guybrush** [visionmedia/masteringnode#10]
in the [modules-chapter](http://github.com/visionmedia/masteringnode/blob/master/chapters/modules.md) is "Asynchronous Require" which is not in nodejs anymore since http://github.com/ry/node/commit/bb08f0c219bf4ca99b1129f54ef415ce46b01f22

**Comment by tj** [comment]
haha fuck.. yeah saw that patch. will try to update soon

**Comment by tj** [comment]
Removed async require sections. Closed by 765e34ed93e10b06ef2ad5ab181375f8d93e3cac
