### ISSUE TITLE
ePub export?

### ISSUE THREAD

**Issue by chuckharmston** [visionmedia/masteringnode#2]
PDFs are unsexy...I'd love some sweet, sweet iPad love!

**Comment by zefhemel** [comment]
Indeed! Definitely would like a ePub version as well.

**Comment by tj** [comment]
I have not personally tried the epub version (yet) but should work

**Comment by zefhemel** [comment]
It does work

**Comment by tj** [comment]
Ah yes it does just checked it out on the iPad last night. Would be good to get an image for the front page tho
